"""Adiciona nome_paciente à tabela consulta

Revision ID: 3a292a2a981b
Revises: 
Create Date: 2024-12-04 18:30:56.438714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a292a2a981b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_paciente', sa.String(length=150), nullable=False))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('hora',
               existing_type=sa.TIME(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('data_fim',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('fabricante',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('validade',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.alter_column('validade',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('fabricante',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.alter_column('data_fim',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('data_inicio',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.String(length=100),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('nome_paciente')

    # ### end Alembic commands ###
